# .travis.yml
 
language: php
 
sudo: false
 
php:
  - 7.0
  - 7.1
 
script:
  # Run your tests here.
  - echo 'Tested'

before_deploy:
  - mkdir build
  - cp LICENSE build
  - cp README.txt build
  - cp remove-medium-cross-links.php build
 
deploy:
  - provider: wordpress-plugin
    edge:
      source: netdesignr/remove-admin-toolbar
      branch: master
    on:
      php: 7.1
      tags: true
      repo: netdesignr/remove-admin-toolbar
    slug: remove-admin-toolbar
    username: $SVN_USERNAME
    password: $SVN_PASSWORD
    build_dir: build 